version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    open-pull-requests-limit: 5
    # Optionally add reviewers or assignees if desired
    # reviewers:
    #   - c4snipes

  - package-ecosystem: docker
    directory: "/docker"
    schedule:
      interval: monthly
    labels:
      - dependencies
