services:
  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "if [ -f package-lock.json ]; then npm ci; else npm i; fi && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"

